name: Docker Security
on:
  push:
    branches: [main]
  schedule:
    - cron: '49 5 * * 3'
  workflow_dispatch:
permissions: {}
jobs:
  docker-security:
    permissions:
      contents: read
      security-events: write
    uses: rknightion/.github/.github/workflows/docker-security.yml@afb6465863055fdc848fc71c8ef94af0aa813f42 # v1.20.1
